network:
  version: 2
  ethernets:
    eno1:
      dhcp4: false
    br-ex:
      dhcp4: false
      addresses:
        - 10.1.141.25/24
      nameservers:
        addresses:
          - 10.1.137.3
          - 10.1.137.4
        search:
          - cba.local
      routes:
        - to: default
          via: 10.1.141.254

--------------------------------------------------------------------------------

network:
  version: 2
  ethernets:
    eno1:
      dhcp4: false
    br-ex:
      dhcp4: false
      addresses:
        - 10.1.141.26/24
      nameservers:
        addresses:
          - 10.1.137.3
          - 10.1.137.4
        search:
          - cba.local
      routes:
        - to: default
          via: 10.1.141.254

